# Generated by Django 6.0.3 on 2026-04-03 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, max_length=2200)),
                ('audio_name', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_artist', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1080)),
                ('height', models.IntegerField(default=1920)),
                ('view_count', models.BigIntegerField(default=0)),
                ('share_count', models.BigIntegerField(default=0)),
                ('disable_comments', models.BooleanField(default=False)),
                ('hide_like_count', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reels',
                'ordering': ['-created_at'],
            },
        ),
    ]
