# Generated by Django 6.0.3 on 2026-04-03 10:18

import apps.stories.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_url', models.URLField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('text_position_x', models.FloatField(default=0.5)),
                ('text_position_y', models.FloatField(default=0.5)),
                ('background_color', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(default=5)),
                ('expires_at', models.DateTimeField(default=apps.stories.models.story_expiry)),
                ('is_highlight', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'story_highlights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'story_reactions',
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'story_views',
            },
        ),
    ]
