# Generated by Django 6.0.3 on 2026-04-03 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('like_post', 'Liked your post'), ('like_reel', 'Liked your reel'), ('like_comment', 'Liked your comment'), ('comment', 'Commented on your post'), ('comment_reel', 'Commented on your reel'), ('reply', 'Replied to your comment'), ('follow', 'Started following you'), ('follow_request', 'Requested to follow you'), ('follow_accept', 'Accepted your follow request'), ('mention_post', 'Mentioned you in a post'), ('mention_comment', 'Mentioned you in a comment'), ('tag_post', 'Tagged you in a post'), ('story_reaction', 'Reacted to your story'), ('story_reply', 'Replied to your story')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.comment')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
